require("nvim-treesitter.configs").setup {
    ensure_installed = {
        "rust",
        "c",
        "go",
        "gomod",
        "clojure",
        "scheme",
        "fennel",
        "lua",
        "yaml",
        "toml",
        "json",
        "bash",
        "python",
        "svelte",
        "typescript",
        "javascript",
        "http",
        "html",
        "scss",
        "css",
        "markdown",
        "markdown_inline",
        "query",
        "vim",
        "regex",
        "latex",
    },
    highlight = {
        enable = true,
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "gri",
            scope_incremental = "grc",
            node_decremental = "grd",
        },
    },
    query_linter = {
        enable = false,
        use_virtual_text = true,
        lint_events = { "BufWrite", "CursorHold" },
    },
    autopairs = {
        enable = true,
    },
    rainbow = {
        enable = true,
        extended_mode = true,
        colors = {
            "#89ddff",
            "#72aaff",
            "#82aaff",
            "#c792ea",
            "#bb80b3",
            "#a1bfff",
            "#d5adef",
            "#c0d4ff",
        },
    },
    yati = {
        enable = true,
    },
    indent = {
        enable = false,
    },
}
