#!/bin/sh

picom &
numlockx on &
xwallpaper --stretch ~/my-stuff/Pictures/wallpapers/vscode.jpg &
redshift &
playerctld &
setxkbmap us,cz  ,qwerty -option 'ctrl:nocaps' 'grp:ctrls_toggle' &
lxpolkit &
xrdb .config/x11/xresources &
killalll emacs ; /usr/bin/emacs --daemon &
xset r rate 400 50 &
xclickroot -l xmenu.sh &
/usr/bin/pipewire &
killall dwmStatus ; dwmStatus &
