#!/bin/bash

picom &
numlockx on &
xwallpaper --stretch ~/my-stuff/Pictures/wallpapers/dwm-unix.png &
redshift &
dunst &
playerctld &
setxkbmap us,cz ,qwerty -option 'ctrl:nocaps' 'grp:ctrls_toggle' &
xcape -e "Control_L=Escape"
lxpolkit &
xrdb .config/x11/xresources &
killalll emacs ; /usr/bin/emacs --daemon &
xset r rate 400 50 &
xclickroot -l xmenu.sh &
killall dwmStatus ; dwmStatus &
