#! /bin/bash 

echo 🕙 $(date +'%H:%M:%S')

case $BUTTON in
  1) notify-send " " "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")";;
  2) st -e nvim .local/bin/clock;;
  3) notify-send "Appointments" "$(calcurse -d7)" ;;
  4) st -e nvim .config/dwmblocks/blocks.h;;
  5) st -e nvim .config/dwm/config.def.h;;
esac
