#!/bin/bash

state="Czech"

[ "$(stat -c %y .cache/corona | awk -F':' '{print $1}')" != "$(date +'%Y-%m-%d %H')" ] && curl -s https://corona-stats.online/CZ > ~/.cache/corona

grep $state ~/.cache/corona | sed 's/\x1b\[[0-9;]*m//g ; s/\s*//g ; s/│/;/g' | awk -F';' '{print "😷 "$3}'
deaths=$(grep $state ~/.cache/corona | sed 's/\x1b\[[0-9;]*m//g ; s/\s*//g ; s/│/;/g' | awk -F';' '{print $5}')

case $BUTTON in
  1) notify-send "deaths" "💀 $deaths";;
  2) st -e nvim .local/bin/corona;;
  4) st -e nvim .config/dwmblocks/blocks.h;;
  5) st -e nvim .config/dwm/config.def.h;;
esac

