#!/bin/bash

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

printf " 🌐 %4sB %4sB\\n" $(numfmt --to=iec $rx) $(numfmt --to=iec $tx)

case $BUTTON in
  1) firefox suckless.org;;
  2) st -e nvim .local/bin/network;;
  3) firefox wiki.archlinux.org;;
  4) st -e nvim .config/dwmblocks/blocks.h;;
  5) st -e nvim .config/dwm/config.def.h;;
esac
