vim.g.mapleader = " "
vim.o.syntax = 'enable'
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.path = vim.o.path .. '**'
vim.o.wildmenu = true
vim.o.wildignore = '**/.git/*'
vim.o.incsearch = true
vim.o.hidden = true
vim.o.backup = false
vim.o.timeout = false
vim.o.swapfile = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.clipboard = 'unnamedplus'
vim.o.termguicolors = true
vim.o.guicursor = 'n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait600-blinkoff400-blinkon250-Cursor/lCursor,sm:block-blinkwait175-blinkoff150-blinkon175'
vim.o.autoindent = true
vim.o.cmdheight = 2
vim.o.showmode = false
vim.o.mouse = 'nicra'
vim.o.foldmethod = 'syntax'
vim.o.foldnestmax = 10
vim.o.foldenable = false
vim.o.foldlevel = 2
vim.o.smartcase = true
vim.o.ignorecase = true
vim.o.errorbells = false
vim.o.expandtab = true
vim.o.smarttab = true
vim.o.smartindent = true
vim.o.tabstop = 4
vim.o.softtabstop = vim.o.tabstop
vim.o.shiftwidth = vim.o.tabstop
vim.o.undofile = true
vim.o.undodir = '/home/m3/.config/nvim/undo'
vim.o.undolevels = 10000000
vim.o.undoreload = 10000000
vim.o.fillchars = 'vert:│'
vim.o.scrolloff = 7
vim.o.signcolumn = 'yes'
vim.o.completeopt = 'menuone,noinsert,noselect'
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.o.updatetime = 50
vim.o.list = true
vim.o.listchars = 'eol:↴,trail:·,tab:» ,nbsp:␣,extends:»'
