#!/usr/bin/env bash

answer=$(echo "$1" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
menu=$(command -v dmenu)
if [ $1 != "" ]; then
    choice="$1 = "
else
    choice=
fi

while [[ $# -gt 0 && $1 != "--" ]]; do
    shift
done
[[ $1 == "--" ]] && shift

# Actions
action=$(echo -e "Copy to clipboard\nClear\nClose" | $menu "$@" -p "$choice$answer")
case $action in
    "Copy to clipboard") echo -n "$answer" | xclip -selection clipboard ;;
    "") ;;
    *) $0 "$answer $action" "--dmenu=$menu" "--" "$@" ;;
esac
